server {
    # Écoute uniquement sur le port 443 en SSL (HTTPS)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Nom de domaine défini dans le sujet
    server_name authomas.42.fr;

    # Protocole TLS requis par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Dossier racine où se trouvent les fichiers WordPress
    root /var/www/html;
    index index.php index.html index.htm;

    # Gestion des routes
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Redirection des requêtes PHP vers le conteneur WordPress (FastCGI)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}